#!/usr/bin/env python3
"""Split the program ROM into assembly/data segments and rebuild it byte-identically.

splits.txt lists where each segment starts and what builds it:

    0x000000 bin  vectors
    0x000400 asm
    0x001260 c    src/rom_header.c
    0x001278 asm
    0x0313fc bin  data

A segment runs up to the next line's address (the last one to the end of the
ROM). `asm` segments are generated by `split` from build/prog.bin, cut further
at function-group boundaries so each file stays readable. `c` segments are
compiled with SHC using the flags in the source's first-line header, and their
external symbols come from symbols.txt. `bin` segments are .incbin'd.

usage: build.py split     regenerate asm/ and build/bin/ from build/prog.bin
       build.py build     assemble, compile, link, compare against the ROM
       build.py check     build, then split the image back into 2b.u21/1b.u22
                          and compare those against the original EPROM dumps
"""
import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import fn  # noqa: E402

ROM_SIZE = 0x100000
ASM = ROOT / "asm"
BUILD = ROOT / "build"
OBJ = BUILD / "obj"
BIN = BUILD / "bin"
SHCC = ROOT / "tools" / "shc_probe" / "shcc.sh"
SHC_VERSION = "shc-v5.0r32"
AS = ["sh-elf-as", "--isa=sh2", "--big"]
HEADER_FLAGS = re.compile(r"flags:\s*([^*\n]+?)\s*\*/")
MAX_ASM_FILE = 0x2000  # cut long asm runs at the nearest group boundary


def read_splits():
    segs = []
    for line in (ROOT / "splits.txt").read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        segs.append([int(parts[0], 16), parts[1], parts[2] if len(parts) > 2 else None])
    segs.sort()
    out = []
    for i, (a, kind, arg) in enumerate(segs):
        end = segs[i + 1][0] if i + 1 < len(segs) else ROM_SIZE
        out.append((a, end, kind, arg))
    return out


def read_symbols():
    syms = {}
    for line in (ROOT / "symbols.txt").read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            name, addr = line.split()[:2]
            syms[name] = int(addr, 16)
    return syms


# ---------------------------------------------------------------- split

def asm_pieces(segs):
    """Cut every asm segment into files at pool-group boundaries."""
    bounds = sorted({s for s, _, _, _ in fn.units()})
    pieces = []
    for start, end, kind, _ in segs:
        if kind != "asm":
            continue
        a = start
        while a < end:
            b = end
            if end - a > MAX_ASM_FILE:
                near = [x for x in bounds if a + 0x100 <= x <= a + MAX_ASM_FILE]
                far = [x for x in bounds if a + MAX_ASM_FILE < x < end]
                if near:
                    b = near[-1]
                elif far:
                    b = far[0]  # one group bigger than MAX_ASM_FILE
            pieces.append((a, b))
            a = b
    return pieces


def pool_targets(lo, hi):
    """Addresses read as data by pc-relative loads anywhere in [lo, hi)."""
    data = {}
    for i in fn.MD.disasm(fn.ROM[lo:hi], lo):
        if i.mnemonic in ("mov.l", "mova") and i.op_str.startswith("0x"):
            a = int(i.op_str.split(",")[0], 16)
            data[a] = data[a + 2] = True
        elif i.mnemonic == "mov.w" and i.op_str.startswith("0x"):
            data[int(i.op_str.split(",")[0], 16)] = True
    return data


def render(a0, a1, funcs, globals_, data, raw=frozenset()):
    """Assembly for [a0, a1). Lines are tagged with their address so a failed
    line can be swapped for its raw halfword on the next pass."""
    labels = set()
    body = []
    pc = a0
    while pc < a1:
        w = fn.hw(pc)
        ins = None
        if pc not in data and pc not in raw:
            ins = next(fn.MD.disasm(fn.ROM[pc:pc + 2], pc), None)
        text = None
        if ins is not None:
            op = ins.op_str.replace(" ", "")
            m = re.match(r"0x([0-9a-f]+)(.*)", op)
            if m:
                t = int(m[1], 16)
                if a0 <= t < a1:
                    labels.add(t)
                    op = f".L{t:06x}{m[2]}"
                elif ins.mnemonic in ("bsr", "bra") and t in globals_:
                    op = f"func_{t:06x}{m[2]}"
                else:
                    op = None  # target in another file: keep the raw encoding
            if op is not None:
                text = f"\t{ins.mnemonic}\t{op}" if op else f"\t{ins.mnemonic}"
        if text is None:
            text = f"\t.short\t0x{w:04x}"
        body.append((pc, text))
        pc += 2
    out = [f"/* 0x{a0:06x}-0x{a1:06x}, generated by tools/build.py split */", "\t.text"]
    by_pc = dict(body)
    for pc, text in body:
        if pc in funcs:
            out.append(f"\n\t.global\tfunc_{pc:06x}\nfunc_{pc:06x}:")
        elif pc in labels:
            out.append(f".L{pc:06x}:")
        out.append(f"{text}\t/* {pc:06x} */")
    return "\n".join(out) + "\n", by_pc


def assemble_bytes(src: Path, obj: Path):
    r = subprocess.run([*AS, "-o", str(obj), str(src)], capture_output=True, text=True)
    if r.returncode:
        return None, r.stderr
    raw = subprocess.run(["sh-elf-objcopy", "-O", "binary", "-j", ".text", str(obj), "/dev/stdout"],
                         capture_output=True, check=True).stdout
    return raw, ""


def split() -> None:
    segs = read_splits()
    ASM.mkdir(exist_ok=True)
    OBJ.mkdir(parents=True, exist_ok=True)
    BIN.mkdir(parents=True, exist_ok=True)
    for old in ASM.glob("*.s"):
        old.unlink()
    for start, end, kind, name in segs:
        if kind == "bin":
            (BIN / f"{start:06x}.bin").write_bytes(fn.ROM[start:end])
    pieces = asm_pieces(segs)
    lo = min(a for a, _ in pieces)
    hi = max(b for _, b in pieces)
    funcs = set(fn.call_targets())
    # Only functions that start in an asm file can be referenced by name.
    in_asm = {f for f in funcs if any(a <= f < b for a, b in pieces)}
    data = pool_targets(lo, hi)
    total_raw = 0
    for a, b in pieces:
        raw = set()
        src = ASM / f"{a:06x}.s"
        for _ in range(50):
            text, by_pc = render(a, b, in_asm, in_asm, data, frozenset(raw))
            src.write_text(text)
            got, err = assemble_bytes(src, OBJ / f"{a:06x}.chk.o")
            if got is None:
                # Can't resolve cross-file names here; they are checked at link.
                bad = set()
                for m in re.finditer(r":(\d+): Error", err):
                    line = src.read_text().splitlines()[int(m[1]) - 1]
                    t = re.search(r"/\* ([0-9a-f]{6}) \*/", line)
                    if t:
                        bad.add(int(t[1], 16))
                if not bad:
                    sys.exit(f"{src}: assembler failed:\n{err}")
                raw |= bad
                continue
            want = fn.ROM[a:b]
            # Cross-file bsr/bra to func_ symbols assemble as 0 displacement
            # before linking; only compare what the file decides by itself.
            diff = {a + o for o in range(0, len(want), 2)
                    if got[o:o + 2] != want[o:o + 2]
                    and not re.match(r"\t(bsr|bra)\tfunc_", by_pc.get(a + o, ""))}
            if len(got) != len(want):
                diff.add(a + min(len(got), len(want)) // 2 * 2)
            if not diff:
                break
            raw |= diff
        else:
            sys.exit(f"{src}: could not converge")
        (OBJ / f"{a:06x}.chk.o").unlink(missing_ok=True)
        total_raw += len(raw)
    print(f"split: {len(pieces)} asm files, {total_raw} halfwords forced to .short")


# ---------------------------------------------------------------- build

def c_flags(src: Path) -> list:
    m = HEADER_FLAGS.search(src.read_text().split("\n", 1)[0])
    return m[1].split() if m else []


def build() -> Path:
    segs = read_splits()
    syms = read_symbols()
    OBJ.mkdir(parents=True, exist_ok=True)
    objs = []  # (start, object)
    for start, end, kind, arg in segs:
        if kind == "bin":
            s = OBJ / f"bin_{start:06x}.s"
            s.write_text(f'\t.text\n\t.incbin\t"{BIN / f"{start:06x}.bin"}"\n')
            o = OBJ / f"bin_{start:06x}.o"
            subprocess.run([*AS, "-o", str(o), str(s)], check=True)
            objs.append((start, o))
        elif kind == "c":
            src = ROOT / arg
            o = OBJ / (src.stem + ".o")
            if not o.exists() or o.stat().st_mtime < src.stat().st_mtime:
                subprocess.run([str(SHCC), SHC_VERSION, str(o), str(src), *c_flags(src)], check=True)
            objs.append((start, o))
    for s in sorted(ASM.glob("*.s")):
        a = int(s.stem, 16)
        o = OBJ / f"{s.stem}.o"
        if not o.exists() or o.stat().st_mtime < s.stat().st_mtime:
            subprocess.run([*AS, "-o", str(o), str(s)], check=True)
        objs.append((a, o))
    objs.sort()

    ld = ["SECTIONS", "{", "\t.text 0x0 :", "\t{"]
    for a, o in objs:
        ld.append(f'\t\tASSERT(. == 0x{a:06x}, "{o.name} does not start at 0x{a:06x}");')
        ld.append(f"\t\t{o}(.text)")
    ld += [f'\t\tASSERT(. == 0x{ROM_SIZE:06x}, "image is not 0x{ROM_SIZE:x} bytes");', "\t}",
           "\t/DISCARD/ : { *(.comment) }", "}"]
    ld += [f"_{name} = 0x{addr:08x};" for name, addr in sorted(syms.items())]
    script = BUILD / "rom.ld"
    script.write_text("\n".join(ld) + "\n")
    elf = BUILD / "tgm2p.elf"
    subprocess.run(["sh-elf-ld", "-T", str(script), "-o", str(elf)], check=True)
    out = BUILD / "tgm2p.bin"
    subprocess.run(["sh-elf-objcopy", "-O", "binary", "-j", ".text", str(elf), str(out)], check=True)
    return out


def compare(out: Path) -> bool:
    got, want = out.read_bytes(), fn.ROM
    ok = got == want
    h = hashlib.sha1(got).hexdigest()
    if ok:
        print(f"build/tgm2p.bin OK  sha1 {h}")
    else:
        first = next((i for i in range(min(len(got), len(want))) if got[i] != want[i]), min(len(got), len(want)))
        print(f"build/tgm2p.bin MISMATCH  sha1 {h}  first diff at 0x{first:06x}  "
              f"(len 0x{len(got):x} vs 0x{len(want):x})")
    return ok


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["split", "build", "check"])
    args = ap.parse_args()
    if args.cmd == "split":
        split()
        return
    ok = compare(build())
    if args.cmd == "check" and ok:
        r = subprocess.run([sys.executable, str(ROOT / "tools" / "interleave.py"), "split",
                            str(BUILD / "tgm2p.bin"), "--check"])
        ok = r.returncode == 0
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
